# install-cli.ps1 — Install Vyper CLI as a globally-available command
#
# Usage: powershell -ExecutionPolicy Bypass -File scripts/install-cli.ps1
#
# This script:
#   1. Creates a venv at ~/.vyper/venv/
#   2. Installs the CLI package in development mode
#   3. Creates a vyper.cmd wrapper in a directory on PATH
#   4. Adds the wrapper directory to PATH if needed

param(
    [string]$InstallDir = "$env:USERPROFILE\.vyper",
    [switch]$SystemWide
)

$ErrorActionPreference = "Stop"
$VyperRoot = $InstallDir
$VenvDir = Join-Path $VyperRoot "venv"
$ScriptDir = Join-Path $VyperRoot "bin"
$ProjectDir = Split-Path -Parent $PSScriptRoot

Write-Host "╔══════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║       Vyper CLI Installer                ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ── Step 1: Create directories ──────────────────────────────
Write-Host "📁 Creating directories..." -ForegroundColor Yellow
New-Item -ItemType Directory -Path $VyperRoot -Force | Out-Null
New-Item -ItemType Directory -Path $ScriptDir -Force | Out-Null

# ── Step 2: Create virtual environment ──────────────────────
Write-Host "🐍 Creating Python virtual environment..." -ForegroundColor Yellow
if (Test-Path $VenvDir) {
    Write-Host "  Removing existing venv..." -ForegroundColor DarkYellow
    Remove-Item -Recurse -Force $VenvDir
}

$python = "python"
if ($SystemWide) {
    $python = "py -3.11"
}

& $python -m venv $VenvDir
if (-not $?) {
    Write-Host "❌ Failed to create virtual environment" -ForegroundColor Red
    exit 1
}
Write-Host "  ✅ Virtual environment created" -ForegroundColor Green

# ── Step 3: Activate and install ─────────────────────────────
$pip = Join-Path $VenvDir "Scripts\pip.exe"
$pythonExe = Join-Path $VenvDir "Scripts\python.exe"

Write-Host "📦 Installing Vyper CLI dependencies..." -ForegroundColor Yellow
& $pip install --quiet -r (Join-Path $ProjectDir "cli\requirements.txt")
if (-not $?) {
    Write-Host "❌ Failed to install dependencies" -ForegroundColor Red
    exit 1
}

# Install the package in development mode
Write-Host "📦 Installing Vyper CLI package..." -ForegroundColor Yellow
& $pip install --quiet -e $ProjectDir
if (-not $?) {
    Write-Host "❌ Failed to install Vyper CLI" -ForegroundColor Red
    exit 1
}
Write-Host "  ✅ Dependencies installed" -ForegroundColor Green

# ── Step 4: Create vyper.cmd wrapper ────────────────────────
$wrapperPath = Join-Path $ScriptDir "vyper.cmd"
$wrapperContent = @"
@echo off
"${pythonExe}" -m cli %*
"@

Set-Content -Path $wrapperPath -Value $wrapperContent -Encoding ASCII
Write-Host "  ✅ Created vyper.cmd wrapper" -ForegroundColor Green

# ── Step 5: Add to PATH if not already ──────────────────────
$currentPath = [Environment]::GetEnvironmentVariable("Path", "User")
if ($currentPath -notlike "*$ScriptDir*") {
    Write-Host "🔧 Adding $ScriptDir to user PATH..." -ForegroundColor Yellow
    [Environment]::SetEnvironmentVariable(
        "Path",
        "$currentPath;$ScriptDir",
        "User"
    )
    Write-Host "  ✅ Added to PATH (restart terminal to apply)" -ForegroundColor Green
} else {
    Write-Host "  ✅ Already in PATH" -ForegroundColor Green
}

# ── Step 6: Create default config ───────────────────────────
$configDir = Join-Path $VyperRoot "config"
New-Item -ItemType Directory -Path $configDir -Force | Out-Null
$configFile = Join-Path $VyperRoot "config.yml"
if (-not (Test-Path $configFile)) {
    @"
# Vyper CLI Configuration
# Generated by install-cli.ps1

# Service URLs (Docker Compose host-side ports)
orchestrator_url: http://localhost:8009
scanner_url: http://localhost:8003
exploit_url: http://localhost:8006
reporter_url: http://localhost:8007
dashboard_url: http://localhost:8000
notifier_url: http://localhost:8008
source_url: http://localhost:8002
immunefi_url: http://localhost:8001

# Docker compose project directory (auto-detected if empty)
project_dir: "${ProjectDir}"

# Output preferences
output_format: rich
color: true
show_progress: true

# Docker compose config
compose_file: docker-compose.yml
project_name: sc_auditor
"@ | Set-Content -Path $configFile -Encoding UTF8
    Write-Host "  ✅ Created default config" -ForegroundColor Green
}

# ── Summary ─────────────────────────────────────────────────
Write-Host ""
Write-Host "╔══════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║       Installation Complete!              ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "Vyper CLI installed at:     $ScriptDir" -ForegroundColor Cyan
Write-Host "Virtual environment:        $VenvDir" -ForegroundColor Cyan
Write-Host "Config file:                $configFile" -ForegroundColor Cyan
Write-Host ""
Write-Host "📖 Usage:" -ForegroundColor Yellow
Write-Host "  vyper up              Start all services" -ForegroundColor White
Write-Host "  vyper audit 0xdead... Run audit pipeline" -ForegroundColor White
Write-Host "  vyper dashboard       Open web UI" -ForegroundColor White
Write-Host "  vyper --help          Show help" -ForegroundColor White
Write-Host ""
Write-Host "⚠️  Restart your terminal or run:" -ForegroundColor DarkYellow
Write-Host "  `$env:Path = [Environment]::GetEnvironmentVariable('Path','User')" -ForegroundColor DarkYellow
Write-Host ""
